version: '3.8'
services:
  app:
    container_name: icss_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      icss_db:
        condition: service_healthy
    command: sh -c "chmod +x ./wait-for-db.sh && ./wait-for-db.sh && node app.js"

  icss_db:
    container_name: icss_db
    image: mysql:8
    env_file:
      - .env.local
    environment:
      MYSQL_ROOT_PASSWORD: '111111'
      MYSQL_DATABASE: 'icss_db'
      MYSQL_ROOT_HOST: '%'
      TZ: UTC # 設置時區為 Asia/Taipei
      LANG: C.UTF-8
    volumes:
      - db_data:/var/lib/mysql
      - ./SQL_SCHEMA/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: