# 使用最新的 Node.js LTS 版本
FROM node:lts

# 设置工作目录
WORKDIR /usr/src/app

# 复制 package.json 和 package-lock.json（如果存在）
COPY package*.json ./

# 安装依赖
RUN npm install

# 复制项目文件到工作目录
COPY . .

# 复制 PowerShell 脚本
COPY wait-for-db.ps1 .

# 暴露 8080 端口
EXPOSE 8080

# 设置启动命令
CMD powershell -Command ".\\wait-for-db.ps1 && node app.js"