version: '3.1'
services:
  mysql_icss:
    image: mysql:latest
    container_name: mysql_icss
    privileged: true
    mem_limit: 512m
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '111111'
      MYSQL_DATABASE: 'icss_db'
      MYSQL_ROOT_HOST: '%'
      TZ: 'Asia/Taipei' # 設置時區為 Asia/Taipei
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - back-tier

volumes:
  mysql-volume:

networks:
  back-tier:
    driver: bridge
