version: '3.1'
services:
  mysql_icss:
    image: mysql:8.0
    container_name: mysql_icss
    privileged: true
    mem_limit: 512m
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '111111'
      MYSQL_DATABASE: 'icss_db'
      MYSQL_ROOT_HOST: '%'
      TZ: UTC # 設置時區為 Asia/Taipei
      LANG: C.UTF-8
    volumes:
      - "./db_data/mysql_data:/var/lib/mysql"
      # - "./db_data/my.cnf:/etc/mysql/my.cnf"
      - "./SQL_SCHEMA/init.sql:/docker-entrypoint-initdb.d/mysql_init.sql"
volumes:
  mysql-volume:
