// 課程狀態
const COURSE_STATUS = {
  PENDING: 0,
  ACTIVE: 1,
  INACTIVE: 2,
};

// 課程類型
const COURSE_TYPE = {
  ONLINE: 0,
  OFFLINE: 1,
};

// 推薦課程審核狀態
const RECOMMENDED_COURSE_STATUS = {
  PENDING: 0,
  APPROVED: 1,
  REJECTED: 2,
};

// 用戶角色
const USER_ROLE = {
  ADMIN: 1,
  USER: 0,
  BANNED: -1,
};

const COMMON_RESPONSE_CODE = {
  SUCCESS: 200,
  BAD_REQUEST: 400,
  FORBIDDEN: 403,
  INTERNAL_SERVER_ERROR: 500,
  NOT_FOUND: 404,
  TOKEN_REQUIRED: 401,
  TOKEN_INVALID: 403,
};

const COMMON_RESPONSE_MESSAGE = {
  SUCCESS: "成功",
  ERROR: "錯誤",
  FORBIDDEN: "權限不足",
  USER_BANNED: "用戶已被停用",
  INTERNAL_SERVER_ERROR: "服務器錯誤",
  TOKEN_REQUIRED: "需要 Token",
  TOKEN_INVALID: "Token 無效",
  BAD_REQUEST: "錯誤請求",
};

// 用戶相關訊息
const AUTH_MESSAGE = {
  USER_NOT_FOUND: "用戶不存在",
  USER_INVALID: "用戶無效",
  USER_EXIST: "用戶已存在",
  USER_CREATE_SUCCESS: "用戶新增成功",
  USER_UPDATE_SUCCESS: "用戶更新成功",
  USER_DELETE_SUCCESS: "用戶刪除成功",
  USER_CREATE_FAILED: "用戶新增失敗",
  USER_UPDATE_FAILED: "用戶更新失敗",
  EMAIL_EXIST: "電子郵件已存在",
  USERNAME_EXIST: "用戶名已存在",
  USER_LOGIN_SUCCESS: "用戶登入成功",
  USER_LOGIN_FAILED: "用戶登入失敗",
  USER_REGISTER_SUCCESS: "用戶註冊成功",
  USER_REGISTER_FAILED: "用戶註冊失敗",
  USER_REGISTER_FAILED_EMAIL_EXIST: "用戶註冊失敗，電子郵件已存在",
  USER_REGISTER_FAILED_USERNAME_EXIST: "用戶註冊失敗，用戶名已存在",
  USER_NOT_FOUND_EMAIL: "找不到該電子郵件對應的用戶",
  // 其他訊息
  USERNAME_PASSWORD_EMAIL_REQUIRED: "用戶姓名, 密碼, 電子郵件為必填",
  USERNAME_PASSWORD_REQUIRED: "使用者名稱和密碼為必填",
  USERNAME_PASSWORD_INVALID: "使用者名稱或密碼無效",
  OTP_SEND_SUCCESS: "OTP 發送成功",
  OTP_SEND_FAILED: "OTP 發送失敗",
  OTP_VERIFICATION_SUCCESS: "OTP 驗證成功",
  OTP_VERIFICATION_FAILED: "OTP 驗證失敗",
  OTP_EXPIRED: "OTP 已過期",
  OTP_CODE_REQUIRED: "OTP 碼為必填",
  OTP_CODE_INVALID: "OTP 碼無效",
  OTP_EXPIRES_IN_10_MINUTES: "OTP 碼在 10 分鐘後過期",
  OTP_UPDATE_SUCCESS: "OTP 更新成功",
  OTP_UPDATE_FAILED: "OTP 更新失敗",
  OTP_CODE_NOT_FOUND: "OTP 碼不存在",
  OTP_CODE_EXPIRED: "OTP 碼已過期",
  OTP_CODE_ALREADY_VERIFIED: "OTP 碼已驗證",
};


// 課程錯誤訊息
const COURSE_ERROR_MESSAGE = {
  COURSE_NOT_FOUND: "課程不存在",
  COURSE_PUBLISH_LIMIT_REACHED: "已達到最大上架課程數量限制",
  COURSE_CREATE_FAILED: "課程新增失敗",
  COURSE_UPDATE_FAILED: "課程更新失敗",
  COURSE_DELETE_FAILED: "課程刪除失敗",
  COURSE_DATE_INVALID: "課程日期不能小於報名截止日期",
  COURSE_SIGN_UP_START_DATE_INVALID: "報名開始日期不能大於報名截止日期",
  COURSE_SIGN_UP_END_DATE_INVALID: "報名截止日期不能小於報名開始日期",
  COURSE_MAX_PARTICIPANTS_INVALID: "課程人數不能小於0",
  COURSE_IMAGE_UPLOAD_FAILED: "課程圖片上傳失敗",
  COURSE_IMAGE_URL_INVALID: "課程圖片URL無效",
  COURSE_INSTRUCTOR_INVALID: "講者姓名無效",
  COURSE_TITLE_INVALID: "課程標題無效",
  COURSE_DESCRIPTION_INVALID: "課程描述無效",
  COURSE_PUBLISH_FAILED: "課程上架失敗",
  COURSE_UNPUBLISH_FAILED: "課程下架失敗",
};

// 課程成功訊息
const COURSE_SUCCESS_MESSAGE = {
  COURSE_CREATE_SUCCESS: "課程新增成功",
  COURSE_UPDATE_SUCCESS: "課程更新成功",
  COURSE_DELETE_SUCCESS: "課程刪除成功",
  COURSE_RECOMMEND_SUCCESS: "課程推薦成功",
  COURSE_RECOMMEND_FAILED: "課程推薦失敗",
  COURSE_RECOMMEND_STATUS_SUCCESS: "課程推薦狀態更新成功",
  COURSE_RECOMMEND_STATUS_FAILED: "課程推薦狀態更新失敗",
};

// 報名相關訊息
const REGISTRATION_MESSAGE = {
  REGISTRATION_SUCCESS: "報名成功",
  REGISTRATION_FAILED: "報名失敗",
  REGISTRATION_CANCEL_SUCCESS: "取消報名成功",
  REGISTRATION_CANCEL_FAILED: "取消報名失敗",
};

// 課程圖片上傳相關訊息
const COURSE_IMAGE_UPLOAD_MESSAGE = {
  COURSE_IMAGE_UPLOAD_SUCCESS: "課程圖片上傳成功",
  COURSE_IMAGE_UPLOAD_FAILED: "課程圖片上傳失敗",
  COURSE_IMAGE_UPLOAD_INVALID: "課程圖片無效",
  COURSE_IMAGE_UPLOAD_NOT_FOUND: "未上傳圖片",
};

module.exports = {
  USER_ROLE,
  COMMON_RESPONSE_CODE,
  COMMON_RESPONSE_MESSAGE,
  AUTH_MESSAGE,
  COURSE_STATUS,
  COURSE_TYPE,
  COURSE_ERROR_MESSAGE,
  REGISTRATION_MESSAGE,
  COURSE_IMAGE_UPLOAD_MESSAGE,
  COURSE_SUCCESS_MESSAGE,
  RECOMMENDED_COURSE_STATUS,
};
